services:
  # An old issue: docker-compose will mount volume as root.
  # Workaround: https://github.com/docker/compose/issues/3270
  # (Command 'docker run -v' is not affected)
  file-chown:
    container_name: file-chown
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot:cu124-megapak"
    user: "root"
    volumes: 
      - "./storage:/home/runner"
    command: "chown -R runner:runner /home/runner"

  comfyui:
    init: true
    container_name: comfyui
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot:cu124-megapak"
    ports:
      - "8188:8188"
    volumes:
      - "./storage:/root"
    environment:
      - CLI_ARGS=
    security_opt:
      - "label=type:nvidia_container_t"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
